project_id = "pimsbchtatfyezssynfg"

[functions.chat]
verify_jwt = false

[functions.import-planning-center-people]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.promote-to-admin]
verify_jwt = false
