project_id = "pimsbchtatfyezssynfg"

[functions.chat]
verify_jwt = false

[functions.import-planning-center-people]
verify_jwt = false

[functions.import-pco-attendance]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.promote-to-admin]
verify_jwt = false

[functions.pco-daily-sync]
verify_jwt = false

[functions.drive-audio]
verify_jwt = false
